// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOEnkAFjNfJ0Qt7Vj8TAwryBWOsEPf94',
    appId: '1:1023835792702:web:5ef7d0908a295789eb786f',
    messagingSenderId: '1023835792702',
    projectId: 'family-event-management',
    authDomain: 'family-event-management.firebaseapp.com',
    databaseURL: 'https://family-event-management-default-rtdb.firebaseio.com',
    storageBucket: 'family-event-management.appspot.com',
    measurementId: 'G-1115CP8PWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-M0DWBS5fbhFbuwG5L2MJeI_jGAKkIic',
    appId: '1:1023835792702:android:080dc975c764527feb786f',
    messagingSenderId: '1023835792702',
    projectId: 'family-event-management',
    databaseURL: 'https://family-event-management-default-rtdb.firebaseio.com',
    storageBucket: 'family-event-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8VTh_QClzvt41ArgEWU11i9FstXiHDQ',
    appId: '1:1023835792702:ios:ef0068ec77efc2b7eb786f',
    messagingSenderId: '1023835792702',
    projectId: 'family-event-management',
    databaseURL: 'https://family-event-management-default-rtdb.firebaseio.com',
    storageBucket: 'family-event-management.appspot.com',
    iosBundleId: 'com.example.familyEventsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8VTh_QClzvt41ArgEWU11i9FstXiHDQ',
    appId: '1:1023835792702:ios:ef0068ec77efc2b7eb786f',
    messagingSenderId: '1023835792702',
    projectId: 'family-event-management',
    databaseURL: 'https://family-event-management-default-rtdb.firebaseio.com',
    storageBucket: 'family-event-management.appspot.com',
    iosBundleId: 'com.example.familyEventsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOEnkAFjNfJ0Qt7Vj8TAwryBWOsEPf94',
    appId: '1:1023835792702:web:5bc9fd5b44f76d92eb786f',
    messagingSenderId: '1023835792702',
    projectId: 'family-event-management',
    authDomain: 'family-event-management.firebaseapp.com',
    databaseURL: 'https://family-event-management-default-rtdb.firebaseio.com',
    storageBucket: 'family-event-management.appspot.com',
    measurementId: 'G-NSD3BEE17S',
  );
}
